# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ insecure_platform_warning_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - insecure-platform-warning-dependencies

- name: remove conflicting
  ansible.builtin.apt:
    name: "{{ insecure_platform_warning_conflicting }}"
    state: absent
  tags:
    - insecure-platform-warning-conflicting

- name: upgrade
  ansible.builtin.pip:
    name: "{{ insecure_platform_warning_pip_dependencies }}"
    state: latest
  tags:
    - insecure-platform-warning-upgrade
